# Generated by Django 4.2.4 on 2024-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_no', models.CharField(max_length=255)),
                ('pdf_drw', models.FileField(upload_to='pdf')),
                ('dxf_drw', models.FileField(upload_to='dxf')),
            ],
        ),
    ]
