# Generated by Django 4.2.4 on 2024-01-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='dxf_drw',
            field=models.FileField(upload_to='design/dxf'),
        ),
        migrations.AlterField(
            model_name='design',
            name='pdf_drw',
            field=models.FileField(upload_to='design/pdf'),
        ),
    ]
